name: MongoDB Ping

on:
  schedule:
    - cron: "0 4 * * 0"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install mongoose
      - run: node pingMongo.js
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
